""" Add constraint to book_order

Revision ID: 5b4aa656cb21
Revises: e99a0278b979
Create Date: 2026-01-26 00:34:54.077264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4aa656cb21'
down_revision = 'e99a0278b979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bible_books', schema=None) as batch_op:
        batch_op.alter_column('book_order',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['book_order'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bible_books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('book_order',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
