"""Rename book_order

Revision ID: e99a0278b979
Revises: 
Create Date: 2026-01-25 03:56:28.025403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99a0278b979'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bible_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_order', sa.Integer(), nullable=True))
        batch_op.drop_column('order')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bible_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('book_order')

    # ### end Alembic commands ###
